name: My Build Action

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  my-build-job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout branch
          uses: actions/checkout@v2
        - name: List Workspace
          run: ls ${{ github.workspace }}
        - name: CMake 
          run: cmake --version
