name: My Build Action

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  my-build-job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout branch
          uses: actions/checkout@v2
        - name: List Workspace
          run: ls -la ${{ github.workspace }}
        - name: CMake 
          run: |
            cmake --version
            echo ""
            cmake .
            echo ""
            ls -la ${{ github.workspace }}/CMakeFiles
