name: My Matrix Action

on:
  push:
      branches: [ matrix ]

jobs:
  my-matrix-job:
      runs-on: ${{ matrix.os }}
      env:
        BUILD_DIR: ${{ github.workspace }}${{ matrix.SEP }}build
      strategy:
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
          include:
            - os: macos-latest
              SHELL: bash
              LIST_DIR: ls -la
              SEP: /
              EXEC: ${{env.BUILD_DIR}}/TravisExec
            - os: ubuntu-latest
              SHELL: bash
              LIST_DIR: ls -la
              SEP: /
              EXEC: ${{env.BUILD_DIR}}/TravisExec
            - os: windows-latest
              SHELL: cmd
              LIST_DIR: dir /a
              SEP: \
              EXEC: ${{env.BUILD_DIR}}\Release\TravisExec.exe
      defaults:
        run:
          shell: ${{ matrix.SHELL }}
      
      steps:
        - run: echo "Hello from ${{ matrix.os }}"
        - name: Checkout branch
          uses: actions/checkout@v2
        - name: List Workspace
          run:  ${{matrix.LIST_DIR}} ${{ github.workspace }}
        - name: CMake 
          run: |
            cmake --version
            echo ""
            cmake -B${{env.BUILD_DIR}}
            echo ""
            cmake --build ${{env.BUILD_DIR}} --config Release
            ${{matrix.LIST_DIR}} ${{env.BUILD_DIR}}
             ${{matrix.EXEC}}
            
