name: My Matrix Action

on:
  push:
      branches: [ matrix ]

jobs:
  my-matrix-job:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
          include:
            - os: macos-latest
              LIST_DIR: ls -la
            - os: ubuntu-latest
              LIST_DIR: ls -la
            - os: windows-latest
              LIST_DIR: dir /a

      steps:
        - run: echo "Hello from ${{ matrix.os }}"
        - name: Checkout branch
          uses: actions/checkout@v2
        - name: List Workspace
          run: $LIST_DIR ${{ github.workspace }}
        - name: CMake 
          run: |
            cmake --version
            echo ""
            BUILD_DIR=${{ github.workspace }}/build
            cmake -B$BUILD_DIR
            echo ""
            cmake --build $BUILD_DIR --config Release --target all
            $LIST_DIR $BUILD_DIR/
            $BUILD_DIR/TravisExec
            
